  # ==  Ansible Playbook for AWS Pentesting == 
- hosts: localhost
  connection: local
  become: true
  become_user: root
  become_method: sudo
  vars:
    base_path: /opt

  # == Create Basic Setup of AWS and Docker ==
  tasks:  
    - name: Create AWS Tooling Directory
      file:
        path: "{{ base_path }}/AWS"
        state: directory

    - name: Install packages for AWS Pentesting Environment
      apt:
        name: ['awscli', 'jq', 'docker.io']

    - name: Enable docker service
      ansible.builtin.service:
        name: docker
        enabled: yes
    
    - name: Add user account to Docker Group
      command: usermod -aG docker $USER

    - name: Install AWS-Shell
      pip:
        name: aws-shell
   
  # == Add in AWS GitHub Tooling Structure ==

    - name: Create AWS Directory structure
      file:
        path: "{{ base_path }}/AWS/{{ item }}"
        state: directory
      with_items:
      - Inventory
      - Auditing
      - Offensive

  # == Inventory Checkers == 

    - name: Adding in Git Repo's to Inventory
      git:
        repo={{ item.repo }} recursive=yes
        dest="{{ base_path }}/AWS/Inventory/{{ item.name }}"
      with_items:
      - { repo: 'https://github.com/nccgroup/aws-inventory', name: 'AWS_Inventory'}
      - { repo: 'https://github.com/disruptops/resource-counter', name: 'Resource_Counter'}
      - { repo: 'https://github.com/arkadiyt/aws_public_ips', name: 'Public_IPs'}

  
  # == Auditing Tools == 
    - name: Adding in Git Repo's to Auditing
      git:
        repo={{ item.repo }} recursive=yes
        dest="{{ base_path }}/AWS/Auditing/{{ item.name }}"
      with_items:
      - { repo: 'https://github.com/SecurityFTW/cs-suite', name: 'CS_Suite'}
      - { repo: 'https://github.com/cloudsploit/scans', name: 'CloudSploit'}
      - { repo: 'https://github.com/awslabs/aws-security-benchmark', name: 'AWS_Benchmarks'}
      - { repo: 'https://github.com/duo-labs/cloudmapper', name: 'CloudMapper'}
      - { repo: 'https://github.com/nccgroup/PMapper', name: 'PrincipalMapper'}
      - { repo: 'https://github.com/nccgroup/Scout2', name: 'Scout2'}
      - { repo: 'https://github.com/nccgroup/ScoutSuite', name: 'ScouteSuite'}
      - { repo: 'https://github.com/toniblyx/prowler', name: 'Prowler'}
      - { repo: 'https://github.com/FSecureLABS/awspx', name: 'awspx'}  
  
  # == Offensive Tools == 
  
    - name: Adding in Git Repo's to Offensive
      git:
        repo={{ item.repo }} recursive=yes
        dest="{{ base_path }}/AWS/Offensive/{{ item.name }}"
      with_items:
      - { repo: 'https://github.com/RhinoSecurityLabs/pacu', name: 'Pacu'}
      - { repo: 'https://github.com/andresriancho/nimbostratus', name: 'Nimbostratus'}
      - { repo: 'https://github.com/carnal0wnage/weirdAAL', name: 'WeirdALL'}
      - { repo: 'https://github.com/sa7mon/S3Scanner', name: 'S3Scanner'}
      - { repo: 'https://github.com/prevade/cloudjack', name: 'CloudJack'}
      - { repo: 'https://github.com/dagrz/aws_pwn', name: 'AWS_Pwn'}

  # == Change GitHub Tooling Permissions ==

    - name: Change folder ownership, group and permissions
        file:
          path: /opt/AWS/
          owner: vagrant
          group: vagrant
          recurse: yes
