- hosts: localhost
  connection: local
  become: true
  become_user: root
  become_method: sudo
  tasks:  
    - name: Create Recon Directory
      file:
        path: /home/vagrant/Desktop/Recon
        state: directory

    - name: Create Recon Directory structure
      file:
        path: /home/vagrant/Desktop/Recon/{{ item }}
        state: directory
      with_items:
      # Domain Enumeration
      - ASN_Enumeration
      - Reverse_WHOIS
      # Subdomain Enumeration
      - Linked_Discovery
      - Subdomain_Scraping
      - Subdomain_Bruteforce
      - Alteration_Scanning
      - Subdomain_Takeover
      - Other

    # == ASN Enumeration Setup ==
    - name: Adding in Git Repo's to ASN_Enumeration
      git: 
        repo={{ item.repo }} recursive=yes
        dest=/home/vagrant/Desktop/Recon/ASN_Enumeration/{{ item.name }}
      with_items:
      - { repo: 'https://github.com/yassineaboukir/Asnlookup.git', name: 'ASNLookup'}
      - { repo: 'https://github.com/j3ssie/metabigor.git', name: 'MetaBigor'}
    
    # == Reverse WHOIS Setup ==
    - name: Adding in Git Repo's to Reverse_WHOIS
      git: 
        repo={{ item.repo }} recursive=yes
        dest=/home/vagrant/Desktop/Recon/Reverse_WHOIS/{{ item.name }}
      with_items:
      - { repo: 'https://github.com/vysecurity/DomLink.git', name: 'DomLink'} 

    # == Linked and JS Discovery == 
    - name: Adding in Git Repo's to Linked_Discovery
      git: 
        repo={{ item.repo }} recursive=yes
        dest=/home/vagrant/Desktop/Recon/Linked_Discovery/{{ item.name }}
      with_items:
      - { repo: 'https://github.com/jaeles-project/gospider.git', name: 'GoSpider'} 
      - { repo: 'https://github.com/hakluke/hakrawler.git', name: 'Hakrawler'} 
      - { repo: 'https://github.com/nsonaniya2010/SubDomainizer.git', name: 'SubDomainizer'}
      - { repo: 'https://github.com/Cillian-Collins/subscraper.git', name: 'SubScraper'}

    # == SubDomain Scraping ==
    - name: Adding in Git Repo's to Subdomain_Scraping
      git: 
        repo={{ item.repo }} recursive=yes
        dest=/home/vagrant/Desktop/Recon/Subdomain_Scraping/{{ item.name }}
      with_items:
      - { repo: 'https://github.com/projectdiscovery/subfinder.git', name: 'SubFinder'} 
      - { repo: 'https://github.com/gwen001/github-search.git', name: 'Github_Search'} 
      - { repo: 'https://github.com/incogbyte/shosubgo.git', name: 'ShoSubGo'}

    # == SubDomain Bruteforce ==
    - name: Adding in Git Repo's to Subdomain_Bruteforce
      git: 
        repo={{ item.repo }} recursive=yes
        dest=/home/vagrant/Desktop/Recon/Subdomain_Bruteforce/{{ item.name }}
      with_items:
      - { repo: 'https://github.com/blechschmidt/massdns.git', name: 'MassDNS'} 
      - { repo: 'https://github.com/projectdiscovery/shuffledns.git', name: 'ShuffleDNS'} 
      - { repo: 'https://github.com/assetnote/commonspeak2.git', name: 'CommonSpeak2'}

    # == Alteration Scanning ==
    - name: Adding in Git Repo's to Alteration_Scanning
      git: 
        repo={{ item.repo }} recursive=yes
        dest=/home/vagrant/Desktop/Recon/Alteration_Scanning/{{ item.name }}
      with_items:
      - { repo: 'https://github.com/infosec-au/altdns.git', name: 'AltDNS'} 

    # == Subdomain Takeover ==
    - name: Adding in Git Repo's to Subdomain_Takeover
      git: 
        repo={{ item.repo }} recursive=yes
        dest=/home/vagrant/Desktop/Recon/Subdomain_Takeover/{{ item.name }}
      with_items:
      - { repo: 'https://github.com/EdOverflow/can-i-take-over-xyz.git', name: 'TakeoverXYZ'} 
      - { repo: 'https://github.com/Ice3man543/SubOver.git', name: 'SubOver'} 
      - { repo: 'https://github.com/projectdiscovery/nuclei.git', name: 'Nuclei'} 

    # == Other ==
    - name: Adding in Git Repo's to Other
      git: 
        repo={{ item.repo }} recursive=yes
        dest=/home/vagrant/Desktop/Recon/Other/{{ item.name }}
      with_items:
      - { repo: 'https://github.com/rastating/dnmasscan.git', name: 'DNMasscan'} 
      - { repo: 'https://github.com/x90skysn3k/brutespray.git', name: 'BruteSpray'} 

    - name: Download Google Dorking script
      get_url: 
        url={{ item }}
        dest=/home/vagrant/Desktop/Recon/Other/GitDork.sh mode=a+x
      with_items:
      - https://gist.githubusercontent.com/jhaddix/77253cea49bf4bd4bfd5d384a37ce7a4/raw/ca20c5d8543ef3404b6032938162790636f89241/Github%2520bash%2520generated%2520search%2520links%2520(from%2520hunter.sh)

    - name: Change folder ownership, group and permissions
      file:
        path: /home/vagrant/Desktop/Recon
        owner: vagrant
        group: vagrant
        recurse: yes
